[package]
name = "moreover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
enigo = "0.0.14"
lazy_static = "1.4.0"
regex = "1.5.4"
serialport = "4.0.1"
toml = "0.5.8"
